name: Tik
description: Tik is a simple GTD app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.3.2+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audioplayers: ^0.19.1
  bot_toast: ^4.0.1
  device_info_plus: ^3.1.0
  dio: ^4.0.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  libwinmedia: ^0.0.5
  sqflite: ^2.0.0+3
  package_info_plus: ^1.0.4
  fluttertoast: 8.0.3
  get: ^4.3.8
  flutter_slidable: 0.6.0
  scoped_model: ^2.0.0-nullsafety.0
  photo_view: ^0.12.0
  shared_preferences: ^2.0.15
  sticky_headers: ^0.2.0
  tray_manager: ^0.1.0
  uni_links: ^0.5.1
  flutter_launcher_icons: ^0.9.0
  eva_icons_flutter: 3.0.0
  flutter_hooks: ^0.18.0
  overlay_support: ^1.2.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  uuid: ^3.0.4
  table_calendar: 3.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_colorpicker: ^1.0.3
  wheel:
    git:
      url: https://github.com/jiangxiaoqiang/wheel.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  archive: ^3.1.5
  msix: ^2.1.3

flutter_icons:
  image_path: "assets/images/translation_engine_icons/reddwarf1024.png"
  android: true
  ios: true

dependency_overrides:
  flutter_secure_storage: 5.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/environments/
    - assets/images/
    - assets/images/flag_icons/
    - assets/translations/
    - assets/cfg/
    - assets/static/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf